apiVersion: v1
kind: Pod
metadata:
 name: helloapp-pf
spec:
 containers:
# THIS IS DEMO!!! CAUTION!!!
 - image: poznajkubernetes/kuard
   name: kuard
# Czesc, STATEK, multistage build, FROM scratch!!!!
 - image: poznajkubernetes/helloapp:8888 
   name: helloapp