apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Poznaj!
          restartPolicy: OnFailure

