apiVersion: v1
kind: Pod
metadata:
  name: pkad-01
  labels:
    name: pkad-01
    app: pkad
spec:
  containers:
  - name: pkad-01
    image: poznajkubernetes/pkad
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: pkad-02
  labels:
    name: pkad-02
    app: pkad
spec:
  containers:
  - name: pkad-02
    image: poznajkubernetes/pkad
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
