apiVersion: v1
kind: PersistentVolume
metadata:
  name: pk-recycle-pv
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/c/poznajkubernetes/volumes/recycle"