apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pkad
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pkad
  minReplicas: 1
  maxReplicas: 10  
  targetCPUUtilizationPercentage: 50