apiVersion: v1
kind: Pod
metadata:
  name: pkad
  labels:
    name: pkad
spec:
  containers:
  - name: pkad
    image: poznajkubernetes/pkad
    env:
    - name: TEST
      value: Poznaj Kubernetes
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
