apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-dep-expression
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: env
        operator: NotIn
        values:
          - prod
      - key: pk
        operator: Exists
      - { key: app, operator: In, values: [ helloapp-dep-expression ] }
  template:
    metadata:
      labels:
        app: helloapp-dep-expression
        env: tst
        pk: "true"
    spec:
      containers:
      - name: helloapp-dep-expression
        image: poznajkubernetes/helloapp:svc
        ports:
        - containerPort: 8080
